data = [
    {"Food": "Chicken Breast", "Category": "Protein", "Calories (kcal)": 165, "Protein (g)": 31, "Carbs (g)": 0, "Fat (g)": 3.6},
    {"Food": "Turkey Breast", "Category": "Protein", "Calories (kcal)": 135, "Protein (g)": 30, "Carbs (g)": 0, "Fat (g)": 1.2},
    {"Food": "Salmon", "Category": "Protein", "Calories (kcal)": 208, "Protein (g)": 20, "Carbs (g)": 0, "Fat (g)": 13},
    {"Food": "Tuna (Canned)", "Category": "Protein", "Calories (kcal)": 132, "Protein (g)": 29, "Carbs (g)": 0, "Fat (g)": 0.6},
    {"Food": "Egg (Whole)", "Category": "Protein", "Calories (kcal)": 155, "Protein (g)": 13, "Carbs (g)": 1.1, "Fat (g)": 11},
    {"Food": "Tofu (Firm)", "Category": "Protein", "Calories (kcal)": 144, "Protein (g)": 15, "Carbs (g)": 3.9, "Fat (g)": 8},
    {"Food": "Cottage Cheese", "Category": "Protein", "Calories (kcal)": 98, "Protein (g)": 11, "Carbs (g)": 3.4, "Fat (g)": 4.3},
    {"Food": "Lentils (Cooked)", "Category": "Protein", "Calories (kcal)": 116, "Protein (g)": 9, "Carbs (g)": 20, "Fat (g)": 0.4},
    {"Food": "Greek Yogurt (Plain, Low Fat)", "Category": "Protein", "Calories (kcal)": 59, "Protein (g)": 10, "Carbs (g)": 3.6, "Fat (g)": 0.4},
    {"Food": "Ground Beef (90% lean)", "Category": "Protein", "Calories (kcal)": 176, "Protein (g)": 25, "Carbs (g)": 0, "Fat (g)": 7.7},
    {"Food": "Brown Rice (Cooked)", "Category": "Carbohydrate", "Calories (kcal)": 123, "Protein (g)": 2.7, "Carbs (g)": 25.6, "Fat (g)": 1},
    {"Food": "Quinoa (Cooked)", "Category": "Carbohydrate", "Calories (kcal)": 120, "Protein (g)": 4.1, "Carbs (g)": 21.3, "Fat (g)": 1.9},
    {"Food": "Oats (Raw)", "Category": "Carbohydrate", "Calories (kcal)": 389, "Protein (g)": 16.9, "Carbs (g)": 66.3, "Fat (g)": 6.9},
    {"Food": "Sweet Potato (Cooked)", "Category": "Carbohydrate", "Calories (kcal)": 86, "Protein (g)": 1.6, "Carbs (g)": 20.1, "Fat (g)": 0.1},
    {"Food": "Apple", "Category": "Carbohydrate", "Calories (kcal)": 52, "Protein (g)": 0.3, "Carbs (g)": 13.8, "Fat (g)": 0.2},
    {"Food": "Banana", "Category": "Carbohydrate", "Calories (kcal)": 89, "Protein (g)": 1.1, "Carbs (g)": 22.8, "Fat (g)": 0.3},
    {"Food": "Orange", "Category": "Carbohydrate", "Calories (kcal)": 47, "Protein (g)": 0.9, "Carbs (g)": 11.8, "Fat (g)": 0.1},
    {"Food": "Blueberries", "Category": "Carbohydrate", "Calories (kcal)": 57, "Protein (g)": 0.7, "Carbs (g)": 14.5, "Fat (g)": 0.3},
    {"Food": "Whole Wheat Bread", "Category": "Carbohydrate", "Calories (kcal)": 247, "Protein (g)": 12, "Carbs (g)": 41, "Fat (g)": 3.5},
    {"Food": "Chickpeas (Cooked)", "Category": "Carbohydrate", "Calories (kcal)": 164, "Protein (g)": 8.9, "Carbs (g)": 27.4, "Fat (g)": 2.6},
    {"Food": "Almonds", "Category": "Fat", "Calories (kcal)": 579, "Protein (g)": 21, "Carbs (g)": 22, "Fat (g)": 50},
    {"Food": "Avocado", "Category": "Fat", "Calories (kcal)": 160, "Protein (g)": 2, "Carbs (g)": 8.5, "Fat (g)": 14.7},
    {"Food": "Olive Oil", "Category": "Fat", "Calories (kcal)": 884, "Protein (g)": 0, "Carbs (g)": 0, "Fat (g)": 100},
    {"Food": "Peanut Butter", "Category": "Fat", "Calories (kcal)": 588, "Protein (g)": 25, "Carbs (g)": 20, "Fat (g)": 50},
    {"Food": "Chia Seeds", "Category": "Fat", "Calories (kcal)": 486, "Protein (g)": 17, "Carbs (g)": 42, "Fat (g)": 31},
    {"Food": "Flax Seeds", "Category": "Fat", "Calories (kcal)": 534, "Protein (g)": 18, "Carbs (g)": 29, "Fat (g)": 42},
    {"Food": "Walnuts", "Category": "Fat", "Calories (kcal)": 654, "Protein (g)": 15, "Carbs (g)": 14, "Fat (g)": 65},
    {"Food": "Sunflower Seeds", "Category": "Fat", "Calories (kcal)": 584, "Protein (g)": 20.8, "Carbs (g)": 20, "Fat (g)": 51},
    {"Food": "Coconut Oil", "Category": "Fat", "Calories (kcal)": 862, "Protein (g)": 0, "Carbs (g)": 0, "Fat (g)": 100},
    {"Food": "Macadamia Nuts", "Category": "Fat", "Calories (kcal)": 718, "Protein (g)": 8, "Carbs (g)": 14, "Fat (g)": 76},
    {"Food": "Broccoli", "Category": "Vegetable", "Calories (kcal)": 34, "Protein (g)": 2.8, "Carbs (g)": 6.6, "Fat (g)": 0.4},
    {"Food": "Spinach", "Category": "Vegetable", "Calories (kcal)": 23, "Protein (g)": 2.9, "Carbs (g)": 3.6, "Fat (g)": 0.4},
    {"Food": "Kale", "Category": "Vegetable", "Calories (kcal)": 49, "Protein (g)": 4.3, "Carbs (g)": 9, "Fat (g)": 0.9},
    {"Food": "Carrots", "Category": "Vegetable", "Calories (kcal)": 41, "Protein (g)": 0.9, "Carbs (g)": 9.6, "Fat (g)": 0.2},
    {"Food": "Bell Peppers (Red)", "Category": "Vegetable", "Calories (kcal)": 31, "Protein (g)": 1, "Carbs (g)": 6, "Fat (g)": 0.3},
    {"Food": "Asparagus", "Category": "Vegetable", "Calories (kcal)": 20, "Protein (g)": 2.2, "Carbs (g)": 3.9, "Fat (g)": 0.1},
    {"Food": "Zucchini", "Category": "Vegetable", "Calories (kcal)": 17, "Protein (g)": 1.2, "Carbs (g)": 3.1, "Fat (g)": 0.3},
    {"Food": "Cauliflower", "Category": "Vegetable", "Calories (kcal)": 25, "Protein (g)": 1.9, "Carbs (g)": 4.9, "Fat (g)": 0},
]
